name: Gefyra Patcher auto-merge
on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - 'main'
    paths:
      - 'Formular/gefyra.rb'

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'gefyra-patcher' }}
    steps:
      - name: Enable auto-merge for gefyra-patcher PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}